plugins {
    id 'base'
    //id 'net.researchgate.release' version '3.1.0'
    id("io.github.simonhauck.release") version "1.5.1"
}

release {
    // preTagCommitMessage = '[release] - pre tag commit: '
    // tagCommitMessage = '[release] - creating tag: '
    // newVersionCommitMessage = '[release] - new version commit: '
    // tagTemplate = 'v${version}'
    versionPropertyFile.set(layout.projectDirectory.file("gradle.properties"))
    releaseCommitMessage.set("chore: Releasing {version}")
    postReleaseCommitAddFiles.set([file("gradle.properties")])
    postReleaseCommitMessage.set("chore: Bump version to {version}")
}

tasks.register('hello') {
    doLast {
        println '===================='
        println 'Hello from the build'
        println '===================='
    }
}

// afterReleaseBuild.dependsOn tasks.hello
pushRelease.finalizedBy tasks.hello

tasks.register('commitRelease') {
    dependsOn('writeReleaseVersion', 'commitReleaseVersion', 'pushRelease')
}
/*

    writeReleaseVersion: This task writes the release version to your version file.
    commitReleaseVersion: This task will create a commit tagged with the release version.
    pushRelease: This task will perform the push operation.
    writePostReleaseVersion: This task with write the post release version to your version file.
    commitPostReleaseVersion: This task will commit the post release version. This commit will not be tagged.
    pushPostRelease: This task will push the post release version.

 */
tasks.register('commitDevelopment') {
    dependsOn('writePostReleaseVersion', 'commitPostReleaseVersion', 'pushPostRelease')
}